### ISSUE TITLE
Update uglifyjs

### ISSUE THREAD

**Issue by janlisse** [sbt/sbt-uglify#17]
Hello,

the sbt plugin currently uses version 2.4.13 of uglifyjs. The upstream code is already far ahead and it would be nice to update to the latest version. The 2.4.13 version especially throws (false) errors
during the asset pipeline invocation:
`[info] Optimizing 1 JavaScript(s) with Uglify
[error] util.error: Use console.error instead`

It's already reported in this [github issue](https://github.com/mishoo/UglifyJS2/issues/791) and fixed in the latest versions.

**Comment by danielnixon** [comment]
I've published a fork based on LolHens's work. Try `addSbtPlugin("org.danielnixon" % "sbt-uglify" % "1.0.7")`. It uses UglifyJS 2.7.5.
