### ISSUE TITLE
util.error is deprecated

### ISSUE THREAD

**Issue by eximius313** [sbt/sbt-uglify#21]
While running `sbt-uglify` I get:
`[error] (node) util.error is deprecated. Use console.error instead.`

**Comment by johdah** [comment]
@huntc Can you please help with this? It's caused by the underlying uglify version. The webjar needs to be updated first.

**Comment by danielnixon** [comment]
I've published a fork based on LolHens's work. Try `addSbtPlugin("org.danielnixon" % "sbt-uglify" % "1.0.7")`. It uses UglifyJS 2.7.5.

**Comment by mkurz** [comment]
Latest release is using uglify-js 3.16.3 now.
