### ISSUE TITLE
how can I include the public folder?

### ISSUE THREAD

**Issue by Yuliang-Lee** [sbt/sbt-uglify#22]
> The sbt excludeFilter is also available to the uglify scope and defaults to excluding the public folder and extracted Webjars.

I don't want to exclude public folder. 
what should I do??

**Comment by objectmastery** [comment]
Two possible solutions.

If you don't want to exclude anything, you could try putting this into your build.sbt:

```scala
excludeFilter in uglify := HiddenFileFilter
````

Otherwise, if you still want to exclude the Webjars, try using this:
(I haven't tested the code below, so let me know if you get errors)

```scala
excludeFilter in uglify := new SimpleFileFilter({
      f =>
        def fileStartsWith(dir: File): Boolean = f.getPath.startsWith(dir.getPath)
        fileStartsWith((WebKeys.webModuleDirectory in Assets).value)
    }),
```

**Comment by Yuliang-Lee** [comment]
thx
