### ISSUE TITLE
sbt dist causes io.apigee.trireme.core.NodeException

### ISSUE THREAD

**Issue by devDomM** [sbt/sbt-uglify#54]
We have a **play 3.0.3** project and wanted to integrate the sbt-uglify plugin (version **3.0.1**).
Following the instructions `addSbtPlugin("com.github.sbt" % "sbt-uglify" % "3.0.1")` was added to the **plugins.sbt** and the **build.sbt** was adapted for the SbtWeb plugin and the pipelineStages for uglify:
```scala
lazy val root = (project in file(".")).enablePlugins(PlayJava, SbtWeb)
  .settings(
    . . .
    pipelineStages := Seq(uglify)
  )
```

A very simplyfied javascript files is located in the project's **app/assets** folder.

When executing `sbt run` to start the play project, the plugin works as expected and will "uglify" the javascript file. However, when we're trying to create a package for production by executing `sbt dist`, we receive the following exception: 
```
[error] io.apigee.trireme.core.NodeException: No available Node.js implementation matches version null
[error]         at io.apigee.trireme.core.NodeScript.getRegistry(NodeScript.java:177)
[error]         at io.apigee.trireme.core.NodeScript.execute(NodeScript.java:103)
[error]         at com.typesafe.sbt.jse.engines.Trireme.executeJs(Trireme.scala:41)
[error]         at com.typesafe.sbt.jse.SbtJsTask$.executeJsOnEngine(SbtJsTask.scala:197)
...
```

This behaviour can be reproduced by configuring the play-java-ebean-example from the play-samples reposistory.

We also tried to manually add some trireme node dependencies, but without any success.

Is this a bug, or do we still need to configure something we may have missed?

**Comment by mkurz** [comment]
hmm... The new `sbt-uglify` 3.x release should use the local installed node if available.
Where do you package your application for production? On the same dev machine?
Make sure you have node installed on all machines.
What does `node --version` tell you?

**Comment by mkurz** [comment]
Also, do you see [this message](https://github.com/sbt/sbt-js-engine/blob/1.3.6/src/main/scala/com/typesafe/sbt/jse/SbtJsEngine.scala#L89-L91) displayed when packaging your project?

Also do you have `engineType` set in your `build.sbt`?

**Comment by devDomM** [comment]
Thanks for the quick reply!

Yes, I also received the message about Rhino. So we added 
`JsEngineImport.JsEngineKeys.engineType := JsEngineImport.JsEngineKeys.EngineType.Trireme` to our built.sbt
However, this does not have any impact on the occuring exception.

Regarding the node installation, I do not have **node.js** installed. Since `sbt run` works without a locally installed node.js, I assume it should also not be required for `sbt dist`?

**Comment by mkurz** [comment]
> Thanks for the quick reply!

You are welcome :wink: 

> Yes, I also received the message about Rhino. So we added `JsEngineImport.JsEngineKeys.engineType := JsEngineImport.JsEngineKeys.EngineType.Trireme` to our built.sbt However, this does not have any impact on the occuring exception.

Please read the message again, it says `...sbt will use the Rhino based Trireme JavaScript engine instead...` so setting `engineType` to `Trireme` is redundant because this is what happens anyway. So of course this does not have any impact.

Please just totally remove this setting or, even better, set it to `JsEngineImport.JsEngineKeys.EngineType.Node`.
By not setting it, sbt-js-engine will try to detect node and if it can not be found, it falls back to Trireme.

> Regarding the node installation, I do not have **node.js** installed. Since `sbt run` works without a locally installed node.js, I assume it should also not be required for `sbt dist`?
> 
> **Edit:** We tested this on a colleague's machine which has node.js v20 installed. You are correct, with a local installation of node.js the dist command works without any issues. However, I still do not quite understand, why the `sbt run` command is executing uglify without any installation then.

Are you 100% sure when running `sbt run` the file will gets uglified? IMHO uglify runs only when building the prod package... but not in dev mode.

I highly recommend you to use a recent node version on all your machines (like 20 lts) so `sbt-js-engine` will pick it up automatically. (I recommend to use [`nvm`](https://github.com/nvm-sh/nvm) to manage node installation locally - it's similiar to sdkman if you know that)
Even safer would be to set

```sbt
JsEngineImport.JsEngineKeys.engineType := JsEngineImport.JsEngineKeys.EngineType.Node
```

in your projects. That should trigger are clearer exception when node can not be found.

Trireme is totally outdated, there are no new releases anymore and seems unmaintained: https://github.com/apigee/trireme/tags

Actually it's very very likely in the next major sbt-js-engine release I will just remove all other engines except node, so node will then be a requirement to run sbt web plugins like sbt-uglify.

**Comment by devDomM** [comment]
> Please read the message again, it says ...sbt will use the Rhino based Trireme JavaScript engine instead... so setting engineType to Trireme is redundant because this is what happens anyway. So of course this does not have any impact.

This was my misunderstanding. When the engineType is now set to Node, an exception is thrown in dev (sbt run) as well as in prod mode (sbt dist): `play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[IOException: Cannot run program "node"`
This confirms your statement, that node.js has to be installed.

However, I tested again with **Trireme** set as the engineType: The uglifying actually works when `sbt run` is called. I can access a "minified and uglified" version of the javascript through the play assets.

> I highly recommend you to use a recent node version on all your machines (like 20 lts) so sbt-js-engine will pick it up automatically.
Thank you very much for the recommendation, as well as for all the explanations. I think we will have to install node.js on our build servers, so everything will work as expected. 

Nevertheless, I am still a bit curious why Trireme would not require the node.js installation. Not sure if this is relevant, but we tested this exclusively on windows machines.
But since Trireme is outdated and will be removed, as you explained, I am not sure if it's worth to investigate this any further.

**Comment by mkurz** [comment]
Do not spend time with Trireme, it's total wasted time, just use node installed.

> why Trireme would not require the node.js installation

Trireme does not need node.js, Trireme is a node implementation written in java.

> However, I tested again with Trireme set as the engineType:

Did you remove the ugflied file before? To 100% make sure that it gets re-generated,.
Also, which Java version are you using?

**Comment by devDomM** [comment]
> Did you remove the ugflied file before? To 100% make sure that it gets re-generated,.
Also, which Java version are you using?

Yes, cleaned the target folders and compiled the application from scratch and the javascript got uglified with Trireme in dev mode. 
The Windows Machine on which this was tested did not have had any node.js installed yet. The java version is **Temurin-21.0.2+13**

> Do not spend time with Trireme, it's total wasted time, just use node installed.

Fine for me 😄 

Thanks again for your help. I will close this issue then.
