### ISSUE TITLE
How to make sbt-uglify to work with play 2.3

### ISSUE THREAD

**Issue by nonameplum** [sbt/sbt-uglify#6]
Hi,

I read documentation and sbt-uglify tests but it seems that sbt-uglify not work. 

I created simple application using command `activator new play-java` and then cuted folder javascript from public to assets with javascript hello.js file. Also added sbt-uglify to plugins and to pipeline.

You can check this example project on github:
https://github.com/nonameplum/play-uglify-test

Best regards,
Lukas

**Comment by wuhuajie** [comment]
@nonameplum @rtfpessoa, Sorry to bother you. Even I use :Assets in conf/routes,  I still have the problem as @rtfpessoa, 
"I'm using sbt-uglify and the files are being minified correctly, and I can grab both the .js and the .min.js from the assets route but in production it doesn't seem to select the minified version automatically. Any ideas?"
