### ISSUE TITLE
Out of Memory Exception with 60+ JS/CoffeeScript files

### ISSUE THREAD

**Issue by ascreamingweas** [sbt/sbt-uglify#9]
Hello. I have a Play 2.3 application to replicate the errors that I am seeing when using Sbt-Uglify with 60+ JS files.

This works fine when I only have about 20-30, but it starts crashing with Out of Memory exceptions when I try to optimize 60 or more CoffeeScripts. Mind you, this is only when I use versioned assets either on production mode (sbt start or sbt dist) or testing specifically in dev mode (pipelineStages in Assets...).

A link to this example is here: https://github.com/ascreamingweas/Sbt-Uglify-Test. I am using MAC OS 10.10.2. 

Please let me know if there is anything else I can do to help solve this issue. It is really bugging my team.

Thanks!

**Comment by huntc** [comment]
That sounds odd - have you at least tried increasing the memory allocated to sbt?

**Comment by ascreamingweas** [comment]
I have not tried that. I am still fairly new to the Play framework and using sbt plugins in general. Would I add something like: `export SBT_OPTS=-XX:MaxPermSize=256m` to my .bash_profile?

**Comment by huntc** [comment]
Sounds good.

**Comment by ascreamingweas** [comment]
Here is a quick update on this. I have tried increasing my memory that is allocated to sbt (up to 8 GB!) and I it is still crashing with Out of Memory Exceptions.

Any other ideas? My test example (https://github.com/ascreamingweas/Sbt-Uglify-Test) provides a quick reproducible error.

**Comment by huntc** [comment]
Thanks for the sample project - I shall look at it now.

**Comment by huntc** [comment]
This problem appears to be related to in-JVM, Trireme. If you use Node instead then all is well:

```scala
JsEngineKeys.engineType := JsEngineKeys.EngineType.Node
```

That said, I question why you want to uglifying during the compile phase. Instead of:

```scala
pipelineStages in Assets := Seq(uglify)
```

use

```scala
pipelineStages := Seq(uglify)
```

...so then you'll uglify only when packaging your app for production, and you'll have a faster dev cycle. Trireme works under this configuration.

**Comment by ascreamingweas** [comment]
This worked!

Thank you very much for your help with this.

I was only uglifying during dev mode for testing purposes. I switch back before going live.

Again, thank you!
